spring:
  application:
    name: netflix-eureka-naming-server
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
