spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    loadbalancer:
#      ribbon:
#        enable: false
server:
  port: 8100

#currency-exchange-servise:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
