spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:/home/INTEXSOFT/viktoria.vihrova/work/Intexsoft/learning/microservicesV2/spring-cloud-config-server/git-localconfig-repo
server:
  port: 8888
