spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb

#  datasource:
#    url: jdbc:h2:mem:exchange_value
#    username: user
#    password: user
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8000
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
